#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys,json
sys.path.append("/Users/admin/Documents/github/UGFAFAFA/code/")

from flask import Flask, render_template
from flask_socketio import SocketIO, emit
import importlib

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

def log(msg):
    socketio.emit(
        'log', {
            "code":1,
            "data":msg
        }
    )

@app.route('/')
def index():
    return render_template('index.html')

############# base 策略 http ##################
@app.route('/base')
def base():
    from Tusharedata.base import search
    bases = search(keyword="")
    return {
        "code":0,
        "data":bases 
    }


############# analyses 策略 http ##################
@app.route('/analyses')
def analyses():
    from Analyse import analyses
    analyses = analyses()
    return {
        "code":0,
        "data":analyses 
    }



@socketio.on('message')
def handle_message(message):
    socketio.emit('my response', message)
 
@socketio.on('analyse')
def handle_my_custom_event(data):
    rjson = json.loads( str(data, 'utf-8'))
    analyse = importlib.import_module("Analyse."+rjson["name"])
    
    analyse.log = log
    analyse.setup()
    socketio.emit(
        'analyse', {
            "code":0,
            "data":"end"
        }
    )

@socketio.on('analyse1')
def handle_my_custom_event(data):
    from Analyse import Analyse
    param = json.loads(data)

    analyse = Analyse(param["name"])
    analyse.setup(begin=param["begin"],end=param["end"],codes=param["codes"],params=param["params"])
  

    

if __name__ == '__main__':
    socketio.run(app)
