#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!
def common
  
  pod 'CocoaAsyncSocket'
  pod 'SQLite.swift'
  pod 'Alamofire'
  pod 'Charts'
  pod 'Socket.IO-Client-Swift'
  pod 'UGSwiftKit', :path => './UGSwiftKit'
  pod 'UGSwiftKit/UGAnalyse', :path => './UGSwiftKit'
  
#  pod 'SwiftUIKit', :path => './SwiftUIKit'
end

def macOS
pod 'PythonKit', :path => '/Users/admin/Documents/github/PythonKit'
pod 'UGSwiftKit/Appicon', :path => './UGSwiftKit'
end

def iOS
  pod 'SnapKit'
end


target 'apple (iOS)' do
  
  pod 'DoraemonKit/Core', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #必选
  pod 'DoraemonKit/WithLogger', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
#  pod 'DoraemonKit/WithGPS', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
  pod 'DoraemonKit/WithLoad', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
  pod 'DoraemonKit/WithDatabase', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
  pod 'DoraemonKit/WithMLeaksFinder', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
#  pod 'DoraemonKit/WithWeex', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
  
  common
  iOS
end


target 'apple (macOS)' do
  common
  macOS
end
#target 'Tests macOS' do
#  common
#
#end

