source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!
def common
  
  pod 'CocoaAsyncSocket'
  pod 'SQLite.swift'
  pod 'Alamofire'
  pod 'SwiftUIKit', :path => './SwiftUIKit'
end

def macOS

#  /Users/admin/Documents/github/UGFAFAFA/apple/SwiftUIKit
end


target 'apple (iOS)' do
    
    common
end


target 'apple (macOS)' do
  common
end

target 'Tests macOS' do
  common

end
